on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ['build/api/package.json', 'build/types/package.json', 'build/type-definitions/package.json']
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: build
        run: |
          yarn && yarn build
      - uses: JS-DevTools/npm-publish@v1
        name: ${{ matrix.package }}
        with:
          package: ${{ matrix.package }}
          token: ${{secrets.NPM_TOKEN}}
